excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Frameworks
- Products
- Targets Support Files
- ServicePlatform

# ----- Custom rule -----
disabled_rules:
   - trailing_whitespace
   - identifier_name
